sudo: required
language: java
services:
  - docker

jdk:
  - oraclejdk8

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
  - mvn clean install -Pdocker
